# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1531/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1531/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/isaac/Projects/CGI-Web-Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/isaac/Projects/CGI-Web-Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/snap/cmake/1531/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1531/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1531/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaac/Projects/CGI-Web-Server/CMakeFiles /home/isaac/Projects/CGI-Web-Server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaac/Projects/CGI-Web-Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/isaac/Projects/CGI-Web-Server/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named WebServer

# Build rule for target.
WebServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebServer
.PHONY : WebServer

# fast build rule for target.
WebServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/build
.PHONY : WebServer/fast

#=============================================================================
# Target rules for targets named testkit

# Build rule for target.
testkit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testkit
.PHONY : testkit

# fast build rule for target.
testkit/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/testkit.dir/build.make tests/CMakeFiles/testkit.dir/build
.PHONY : testkit/fast

#=============================================================================
# Target rules for targets named core_tests

# Build rule for target.
core_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_tests
.PHONY : core_tests

# fast build rule for target.
core_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/core_tests.dir/build.make tests/CMakeFiles/core_tests.dir/build
.PHONY : core_tests/fast

src/core/dbg.o: src/core/dbg.cc.o
.PHONY : src/core/dbg.o

# target to build an object file
src/core/dbg.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/dbg.cc.o
.PHONY : src/core/dbg.cc.o

src/core/dbg.i: src/core/dbg.cc.i
.PHONY : src/core/dbg.i

# target to preprocess a source file
src/core/dbg.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/dbg.cc.i
.PHONY : src/core/dbg.cc.i

src/core/dbg.s: src/core/dbg.cc.s
.PHONY : src/core/dbg.s

# target to generate assembly for a file
src/core/dbg.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/dbg.cc.s
.PHONY : src/core/dbg.cc.s

src/http/Server.o: src/http/Server.cc.o
.PHONY : src/http/Server.o

# target to build an object file
src/http/Server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/Server.cc.o
.PHONY : src/http/Server.cc.o

src/http/Server.i: src/http/Server.cc.i
.PHONY : src/http/Server.i

# target to preprocess a source file
src/http/Server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/Server.cc.i
.PHONY : src/http/Server.cc.i

src/http/Server.s: src/http/Server.cc.s
.PHONY : src/http/Server.s

# target to generate assembly for a file
src/http/Server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/Server.cc.s
.PHONY : src/http/Server.cc.s

src/http/Session.o: src/http/Session.cc.o
.PHONY : src/http/Session.o

# target to build an object file
src/http/Session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/Session.cc.o
.PHONY : src/http/Session.cc.o

src/http/Session.i: src/http/Session.cc.i
.PHONY : src/http/Session.i

# target to preprocess a source file
src/http/Session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/Session.cc.i
.PHONY : src/http/Session.cc.i

src/http/Session.s: src/http/Session.cc.s
.PHONY : src/http/Session.s

# target to generate assembly for a file
src/http/Session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/Session.cc.s
.PHONY : src/http/Session.cc.s

src/http/handlers/GetHandler.o: src/http/handlers/GetHandler.cc.o
.PHONY : src/http/handlers/GetHandler.o

# target to build an object file
src/http/handlers/GetHandler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/GetHandler.cc.o
.PHONY : src/http/handlers/GetHandler.cc.o

src/http/handlers/GetHandler.i: src/http/handlers/GetHandler.cc.i
.PHONY : src/http/handlers/GetHandler.i

# target to preprocess a source file
src/http/handlers/GetHandler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/GetHandler.cc.i
.PHONY : src/http/handlers/GetHandler.cc.i

src/http/handlers/GetHandler.s: src/http/handlers/GetHandler.cc.s
.PHONY : src/http/handlers/GetHandler.s

# target to generate assembly for a file
src/http/handlers/GetHandler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/GetHandler.cc.s
.PHONY : src/http/handlers/GetHandler.cc.s

src/http/handlers/HeadHandler.o: src/http/handlers/HeadHandler.cc.o
.PHONY : src/http/handlers/HeadHandler.o

# target to build an object file
src/http/handlers/HeadHandler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/HeadHandler.cc.o
.PHONY : src/http/handlers/HeadHandler.cc.o

src/http/handlers/HeadHandler.i: src/http/handlers/HeadHandler.cc.i
.PHONY : src/http/handlers/HeadHandler.i

# target to preprocess a source file
src/http/handlers/HeadHandler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/HeadHandler.cc.i
.PHONY : src/http/handlers/HeadHandler.cc.i

src/http/handlers/HeadHandler.s: src/http/handlers/HeadHandler.cc.s
.PHONY : src/http/handlers/HeadHandler.s

# target to generate assembly for a file
src/http/handlers/HeadHandler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/HeadHandler.cc.s
.PHONY : src/http/handlers/HeadHandler.cc.s

src/http/handlers/OptionsHandler.o: src/http/handlers/OptionsHandler.cc.o
.PHONY : src/http/handlers/OptionsHandler.o

# target to build an object file
src/http/handlers/OptionsHandler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/OptionsHandler.cc.o
.PHONY : src/http/handlers/OptionsHandler.cc.o

src/http/handlers/OptionsHandler.i: src/http/handlers/OptionsHandler.cc.i
.PHONY : src/http/handlers/OptionsHandler.i

# target to preprocess a source file
src/http/handlers/OptionsHandler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/OptionsHandler.cc.i
.PHONY : src/http/handlers/OptionsHandler.cc.i

src/http/handlers/OptionsHandler.s: src/http/handlers/OptionsHandler.cc.s
.PHONY : src/http/handlers/OptionsHandler.s

# target to generate assembly for a file
src/http/handlers/OptionsHandler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/OptionsHandler.cc.s
.PHONY : src/http/handlers/OptionsHandler.cc.s

src/http/handlers/PostHandler.o: src/http/handlers/PostHandler.cc.o
.PHONY : src/http/handlers/PostHandler.o

# target to build an object file
src/http/handlers/PostHandler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/PostHandler.cc.o
.PHONY : src/http/handlers/PostHandler.cc.o

src/http/handlers/PostHandler.i: src/http/handlers/PostHandler.cc.i
.PHONY : src/http/handlers/PostHandler.i

# target to preprocess a source file
src/http/handlers/PostHandler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/PostHandler.cc.i
.PHONY : src/http/handlers/PostHandler.cc.i

src/http/handlers/PostHandler.s: src/http/handlers/PostHandler.cc.s
.PHONY : src/http/handlers/PostHandler.s

# target to generate assembly for a file
src/http/handlers/PostHandler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/handlers/PostHandler.cc.s
.PHONY : src/http/handlers/PostHandler.cc.s

src/http/http.o: src/http/http.cc.o
.PHONY : src/http/http.o

# target to build an object file
src/http/http.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/http.cc.o
.PHONY : src/http/http.cc.o

src/http/http.i: src/http/http.cc.i
.PHONY : src/http/http.i

# target to preprocess a source file
src/http/http.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/http.cc.i
.PHONY : src/http/http.cc.i

src/http/http.s: src/http/http.cc.s
.PHONY : src/http/http.s

# target to generate assembly for a file
src/http/http.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/http.cc.s
.PHONY : src/http/http.cc.s

src/http/mw/Authenticator.o: src/http/mw/Authenticator.cc.o
.PHONY : src/http/mw/Authenticator.o

# target to build an object file
src/http/mw/Authenticator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Authenticator.cc.o
.PHONY : src/http/mw/Authenticator.cc.o

src/http/mw/Authenticator.i: src/http/mw/Authenticator.cc.i
.PHONY : src/http/mw/Authenticator.i

# target to preprocess a source file
src/http/mw/Authenticator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Authenticator.cc.i
.PHONY : src/http/mw/Authenticator.cc.i

src/http/mw/Authenticator.s: src/http/mw/Authenticator.cc.s
.PHONY : src/http/mw/Authenticator.s

# target to generate assembly for a file
src/http/mw/Authenticator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Authenticator.cc.s
.PHONY : src/http/mw/Authenticator.cc.s

src/http/mw/Logger.o: src/http/mw/Logger.cc.o
.PHONY : src/http/mw/Logger.o

# target to build an object file
src/http/mw/Logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Logger.cc.o
.PHONY : src/http/mw/Logger.cc.o

src/http/mw/Logger.i: src/http/mw/Logger.cc.i
.PHONY : src/http/mw/Logger.i

# target to preprocess a source file
src/http/mw/Logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Logger.cc.i
.PHONY : src/http/mw/Logger.cc.i

src/http/mw/Logger.s: src/http/mw/Logger.cc.s
.PHONY : src/http/mw/Logger.s

# target to generate assembly for a file
src/http/mw/Logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Logger.cc.s
.PHONY : src/http/mw/Logger.cc.s

src/http/mw/Parser.o: src/http/mw/Parser.cc.o
.PHONY : src/http/mw/Parser.o

# target to build an object file
src/http/mw/Parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Parser.cc.o
.PHONY : src/http/mw/Parser.cc.o

src/http/mw/Parser.i: src/http/mw/Parser.cc.i
.PHONY : src/http/mw/Parser.i

# target to preprocess a source file
src/http/mw/Parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Parser.cc.i
.PHONY : src/http/mw/Parser.cc.i

src/http/mw/Parser.s: src/http/mw/Parser.cc.s
.PHONY : src/http/mw/Parser.s

# target to generate assembly for a file
src/http/mw/Parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/Parser.cc.s
.PHONY : src/http/mw/Parser.cc.s

src/http/mw/rate_limiters.o: src/http/mw/rate_limiters.cc.o
.PHONY : src/http/mw/rate_limiters.o

# target to build an object file
src/http/mw/rate_limiters.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/rate_limiters.cc.o
.PHONY : src/http/mw/rate_limiters.cc.o

src/http/mw/rate_limiters.i: src/http/mw/rate_limiters.cc.i
.PHONY : src/http/mw/rate_limiters.i

# target to preprocess a source file
src/http/mw/rate_limiters.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/rate_limiters.cc.i
.PHONY : src/http/mw/rate_limiters.cc.i

src/http/mw/rate_limiters.s: src/http/mw/rate_limiters.cc.s
.PHONY : src/http/mw/rate_limiters.s

# target to generate assembly for a file
src/http/mw/rate_limiters.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/mw/rate_limiters.cc.s
.PHONY : src/http/mw/rate_limiters.cc.s

src/http/parsing/parse.o: src/http/parsing/parse.cc.o
.PHONY : src/http/parsing/parse.o

# target to build an object file
src/http/parsing/parse.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/parsing/parse.cc.o
.PHONY : src/http/parsing/parse.cc.o

src/http/parsing/parse.i: src/http/parsing/parse.cc.i
.PHONY : src/http/parsing/parse.i

# target to preprocess a source file
src/http/parsing/parse.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/parsing/parse.cc.i
.PHONY : src/http/parsing/parse.cc.i

src/http/parsing/parse.s: src/http/parsing/parse.cc.s
.PHONY : src/http/parsing/parse.s

# target to generate assembly for a file
src/http/parsing/parse.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/parsing/parse.cc.s
.PHONY : src/http/parsing/parse.cc.s

src/http/routing/Route.o: src/http/routing/Route.cc.o
.PHONY : src/http/routing/Route.o

# target to build an object file
src/http/routing/Route.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/routing/Route.cc.o
.PHONY : src/http/routing/Route.cc.o

src/http/routing/Route.i: src/http/routing/Route.cc.i
.PHONY : src/http/routing/Route.i

# target to preprocess a source file
src/http/routing/Route.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/routing/Route.cc.i
.PHONY : src/http/routing/Route.cc.i

src/http/routing/Route.s: src/http/routing/Route.cc.s
.PHONY : src/http/routing/Route.s

# target to generate assembly for a file
src/http/routing/Route.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/routing/Route.cc.s
.PHONY : src/http/routing/Route.cc.s

src/http/routing/Router.o: src/http/routing/Router.cc.o
.PHONY : src/http/routing/Router.o

# target to build an object file
src/http/routing/Router.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/routing/Router.cc.o
.PHONY : src/http/routing/Router.cc.o

src/http/routing/Router.i: src/http/routing/Router.cc.i
.PHONY : src/http/routing/Router.i

# target to preprocess a source file
src/http/routing/Router.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/routing/Router.cc.i
.PHONY : src/http/routing/Router.cc.i

src/http/routing/Router.s: src/http/routing/Router.cc.s
.PHONY : src/http/routing/Router.s

# target to generate assembly for a file
src/http/routing/Router.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/http/routing/Router.cc.s
.PHONY : src/http/routing/Router.cc.s

src/io/Acceptor.o: src/io/Acceptor.cc.o
.PHONY : src/io/Acceptor.o

# target to build an object file
src/io/Acceptor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Acceptor.cc.o
.PHONY : src/io/Acceptor.cc.o

src/io/Acceptor.i: src/io/Acceptor.cc.i
.PHONY : src/io/Acceptor.i

# target to preprocess a source file
src/io/Acceptor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Acceptor.cc.i
.PHONY : src/io/Acceptor.cc.i

src/io/Acceptor.s: src/io/Acceptor.cc.s
.PHONY : src/io/Acceptor.s

# target to generate assembly for a file
src/io/Acceptor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Acceptor.cc.s
.PHONY : src/io/Acceptor.cc.s

src/io/Socket.o: src/io/Socket.cc.o
.PHONY : src/io/Socket.o

# target to build an object file
src/io/Socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Socket.cc.o
.PHONY : src/io/Socket.cc.o

src/io/Socket.i: src/io/Socket.cc.i
.PHONY : src/io/Socket.i

# target to preprocess a source file
src/io/Socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Socket.cc.i
.PHONY : src/io/Socket.cc.i

src/io/Socket.s: src/io/Socket.cc.s
.PHONY : src/io/Socket.s

# target to generate assembly for a file
src/io/Socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Socket.cc.s
.PHONY : src/io/Socket.cc.s

src/io/Streamer.o: src/io/Streamer.cc.o
.PHONY : src/io/Streamer.o

# target to build an object file
src/io/Streamer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Streamer.cc.o
.PHONY : src/io/Streamer.cc.o

src/io/Streamer.i: src/io/Streamer.cc.i
.PHONY : src/io/Streamer.i

# target to preprocess a source file
src/io/Streamer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Streamer.cc.i
.PHONY : src/io/Streamer.cc.i

src/io/Streamer.s: src/io/Streamer.cc.s
.PHONY : src/io/Streamer.s

# target to generate assembly for a file
src/io/Streamer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/Streamer.cc.s
.PHONY : src/io/Streamer.cc.s

src/io/io.o: src/io/io.cc.o
.PHONY : src/io/io.o

# target to build an object file
src/io/io.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/io.cc.o
.PHONY : src/io/io.cc.o

src/io/io.i: src/io/io.cc.i
.PHONY : src/io/io.i

# target to preprocess a source file
src/io/io.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/io.cc.i
.PHONY : src/io/io.cc.i

src/io/io.s: src/io/io.cc.s
.PHONY : src/io/io.s

# target to generate assembly for a file
src/io/io.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/io/io.cc.s
.PHONY : src/io/io.cc.s

src/logger/Entry.o: src/logger/Entry.cc.o
.PHONY : src/logger/Entry.o

# target to build an object file
src/logger/Entry.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Entry.cc.o
.PHONY : src/logger/Entry.cc.o

src/logger/Entry.i: src/logger/Entry.cc.i
.PHONY : src/logger/Entry.i

# target to preprocess a source file
src/logger/Entry.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Entry.cc.i
.PHONY : src/logger/Entry.cc.i

src/logger/Entry.s: src/logger/Entry.cc.s
.PHONY : src/logger/Entry.s

# target to generate assembly for a file
src/logger/Entry.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Entry.cc.s
.PHONY : src/logger/Entry.cc.s

src/logger/Logger.o: src/logger/Logger.cc.o
.PHONY : src/logger/Logger.o

# target to build an object file
src/logger/Logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Logger.cc.o
.PHONY : src/logger/Logger.cc.o

src/logger/Logger.i: src/logger/Logger.cc.i
.PHONY : src/logger/Logger.i

# target to preprocess a source file
src/logger/Logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Logger.cc.i
.PHONY : src/logger/Logger.cc.i

src/logger/Logger.s: src/logger/Logger.cc.s
.PHONY : src/logger/Logger.s

# target to generate assembly for a file
src/logger/Logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Logger.cc.s
.PHONY : src/logger/Logger.cc.s

src/logger/Sink.o: src/logger/Sink.cc.o
.PHONY : src/logger/Sink.o

# target to build an object file
src/logger/Sink.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Sink.cc.o
.PHONY : src/logger/Sink.cc.o

src/logger/Sink.i: src/logger/Sink.cc.i
.PHONY : src/logger/Sink.i

# target to preprocess a source file
src/logger/Sink.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Sink.cc.i
.PHONY : src/logger/Sink.cc.i

src/logger/Sink.s: src/logger/Sink.cc.s
.PHONY : src/logger/Sink.s

# target to generate assembly for a file
src/logger/Sink.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/logger/Sink.cc.s
.PHONY : src/logger/Sink.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... WebServer"
	@echo "... core"
	@echo "... core_tests"
	@echo "... testkit"
	@echo "... src/core/dbg.o"
	@echo "... src/core/dbg.i"
	@echo "... src/core/dbg.s"
	@echo "... src/http/Server.o"
	@echo "... src/http/Server.i"
	@echo "... src/http/Server.s"
	@echo "... src/http/Session.o"
	@echo "... src/http/Session.i"
	@echo "... src/http/Session.s"
	@echo "... src/http/handlers/GetHandler.o"
	@echo "... src/http/handlers/GetHandler.i"
	@echo "... src/http/handlers/GetHandler.s"
	@echo "... src/http/handlers/HeadHandler.o"
	@echo "... src/http/handlers/HeadHandler.i"
	@echo "... src/http/handlers/HeadHandler.s"
	@echo "... src/http/handlers/OptionsHandler.o"
	@echo "... src/http/handlers/OptionsHandler.i"
	@echo "... src/http/handlers/OptionsHandler.s"
	@echo "... src/http/handlers/PostHandler.o"
	@echo "... src/http/handlers/PostHandler.i"
	@echo "... src/http/handlers/PostHandler.s"
	@echo "... src/http/http.o"
	@echo "... src/http/http.i"
	@echo "... src/http/http.s"
	@echo "... src/http/mw/Authenticator.o"
	@echo "... src/http/mw/Authenticator.i"
	@echo "... src/http/mw/Authenticator.s"
	@echo "... src/http/mw/Logger.o"
	@echo "... src/http/mw/Logger.i"
	@echo "... src/http/mw/Logger.s"
	@echo "... src/http/mw/Parser.o"
	@echo "... src/http/mw/Parser.i"
	@echo "... src/http/mw/Parser.s"
	@echo "... src/http/mw/rate_limiters.o"
	@echo "... src/http/mw/rate_limiters.i"
	@echo "... src/http/mw/rate_limiters.s"
	@echo "... src/http/parsing/parse.o"
	@echo "... src/http/parsing/parse.i"
	@echo "... src/http/parsing/parse.s"
	@echo "... src/http/routing/Route.o"
	@echo "... src/http/routing/Route.i"
	@echo "... src/http/routing/Route.s"
	@echo "... src/http/routing/Router.o"
	@echo "... src/http/routing/Router.i"
	@echo "... src/http/routing/Router.s"
	@echo "... src/io/Acceptor.o"
	@echo "... src/io/Acceptor.i"
	@echo "... src/io/Acceptor.s"
	@echo "... src/io/Socket.o"
	@echo "... src/io/Socket.i"
	@echo "... src/io/Socket.s"
	@echo "... src/io/Streamer.o"
	@echo "... src/io/Streamer.i"
	@echo "... src/io/Streamer.s"
	@echo "... src/io/io.o"
	@echo "... src/io/io.i"
	@echo "... src/io/io.s"
	@echo "... src/logger/Entry.o"
	@echo "... src/logger/Entry.i"
	@echo "... src/logger/Entry.s"
	@echo "... src/logger/Logger.o"
	@echo "... src/logger/Logger.i"
	@echo "... src/logger/Logger.s"
	@echo "... src/logger/Sink.o"
	@echo "... src/logger/Sink.i"
	@echo "... src/logger/Sink.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/isaac/Projects/CGI-Web-Server/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

