if(EXISTS "/home/isaac/Projects/CGI-Web-Server/tests/core_tests[1]_tests.cmake")
  include("/home/isaac/Projects/CGI-Web-Server/tests/core_tests[1]_tests.cmake")
else()
  add_test(core_tests_NOT_BUILT core_tests_NOT_BUILT)
endif()
